name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-formatting:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check formatting with Prettier
        uses: actionsx/prettier@v3
        with:
          args: --check .
